env:
#  - TARGET=CC3D
#  - TARGET=CJMCU
#  - TARGET=NAZE
#  - TARGET=STM32F3DISCOVERY
#  - TARGET=RMDO
#  - TARGET=SPRACINGF3
#  - TARGET=SPRACINGF3EVO
#  - TARGET=SPARKY
#  - TARGET=FURYF3
#  - TARGET=RCEXPLORERF3
#  - TARGET=REVO
  
# use new docker environment
sudo: false

git:
  depth: 5

addons:
  apt:
    packages:
      - build-essential
      - git
      - libc6-i386

# We use cpp for unit tests, and c for the main project.
language: cpp
compiler: clang

before_install: ./install-toolchain.sh

install:
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-5_4-2016q2/bin

before_script: arm-none-eabi-gcc --version
script: ./.travis.sh

cache: 
  apt: true
  directories:
  - $PWD/gcc-arm-none-eabi-5_4-2016q2

notifications:
  #slack: inavflight:UWRoWFJ4cbbpHXT8HJJlAPXa
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/34e795df229478ac3a3b
    on_success: always
    on_failure: always
    on_start: never